### PR TITLE
League container

### PR DESCRIPTION
**Pull request by sagikazarmark**
This PR represents one possible future of the dependency package. It has been fully rewritten (rather deleted most) using [league/container](http://container.thephpleague.com/). It is pretty awesome, some of the features (namely the ServiceProvider idea) is influenced by this package.

I decided to use it because the implementation is mostly the same that I imagined (and started to implement). Also, it is part of the League now which is (IMO) guarantee of great quality and support.

Some more tasks before merging:
- [ ] Rewrite all service providers in all packages
- [ ] Documentation: should we only document features added (and place a link to the original docs) or document the whole feature set?
- [ ] Review the implementation to make sure that everything needed is in place

### CODE REVIEW

**Comment by stevewest** [comment]
Imo full documentation is a good idea. Perhaps the fuel specific parts can have their own section to allow people with existing league/container knowledge to get up to speed quicker.

**Comment by sagikazarmark** [comment]
@stevewest I am not closer to the solution with your comment. ;) You are basically saying that we should document the full container, but mainly the fuel-specific part, right?

Actually I am thinking about placing a link to the league/container docs and only documenting the fuel specific parts.

**Comment by stevewest** [comment]
I am saying we provide some documentation on how it works with fuel. Then an extra part to clarify how our extension differs from the league container.

**Comment by sagikazarmark** [comment]
@stevewest @WanWizard I realized it is almost impossible to migrate every package to the new ServiceProvider architecture one by one using PRs and merging them in the end.

So if you are fine with the direction, I am going to merge this PR, and start working on migration. This mean that the development version of the packages will be broken in the next few hours/days, but I don't think it is not a big problem in this state.

Before the next release we can test everything we need and add any necessary features missing. What do you think?

**Comment by stevewest** [comment]
Sounds ok to me. We are still alpha and it won't break the individual packages, only when you try to use the framework as a whole.

**Pull request merged**
